### ISSUE TITLE
Unable to run an application on https://kopano.demo/webapp

### ISSUE THREAD

**Issue by marijap93** [zokradonh/kopano-docker#101]
After following the instructions here for running a kopano server, I am not able to open the application on https://kopano.demo/webapp. I get the message: "We can’t connect to the server at kopano.demo."

however, I can only open it using https://localhost/webapp.

This means I also have to change to localhost when I want to try out KAPI playground, and I'm not able to sing in or run any queries.

Everything looks okay after docker-compose up, so I am not sure why is this happening.

I am running it on CentOS 7, Docker version 18.09.3 and docker-compose version 1.23.2.

**Comment by fbartels** [comment]
Hi @marijap93,

that sounds a bit like your system does not know that it should resolve your domain to the local system. In case you are really working with the "kopano.demo" domain you need to add this to your local hosts file.

**Comment by marijap93** [comment]
Hi @fbartels,

It works now that I've added kopano.demo to the local hosts file. 

Thank you.
