### ISSUE TITLE
Small adjustment for Mac

### ISSUE THREAD

**Issue by r00tc0d3** [zokradonh/kopano-docker#103]
Hi,
I just checked if it would run on a Mac after LDAP was not working in the past and it is working. I have some remarks. 

If you could change the 'sed -r' to 'sed -E' in the 'setup.sh' script it would both work on linux and mac. I did not tested it yet but for GNU sed -E should be an alias for -r. Also the script is depending on 'jq'. Maybe making a remark about this would be nice because not all machine have this installed. For a Mac a user can install it using `brew install jq`.

The remark about the Mac and LDAP in the README.md can be deleted because you are now using a data volume instead of a bind.

Keep up the good work.

**Comment by fbartels** [comment]
Hi @r00tc0d3,

thanks for your feedback.  A pr to address the points you've mentioned is more than welcome.

> Also the script is depending on 'jq'.

That is not really true. jq is purely optional

**Comment by r00tc0d3** [comment]
jq is optional you are correct, but it will leave a remark.

**Comment by fbartels** [comment]
For ref: https://github.com/zokradonh/kopano-docker/pull/104 (pr about sed)

I have adapted the setup script to also redirect errors. now no message will be printed when jq is not found.

**Comment by r00tc0d3** [comment]
Great!
