### ISSUE TITLE
create a "base" instead of a common image

### ISSUE THREAD

**Issue by fbartels** [zokradonh/kopano-docker#11]
Hi, 

it feels a bit like a missed opportunity to not use a common base image that includes (but not executes) the  "download nightly builds"-script and its already installs the shared dependencies (curl, gpg, ca-certificates, moreutils, locales, apt-transport-https, apt-utils, jq, dumb-ini).

Would you be open to consider merging a change to use a base image instead of the just recently implemented multi stage build with the common image?

**Comment by zokradonh** [comment]
Yes I have also thought about it. I had it this way half a year ago. And I had negative feelings about it. I don't remember what kind of drawbacks I experienced. Well just testing it out is not difficult though.

**Comment by fbartels** [comment]
what do you think about https://github.com/zokradonh/kopano-docker/tree/base ?

**Comment by zokradonh** [comment]
Good, btw I really like the Makefile approach.

>TODO is dumb-init actually used?

I use it in both images as ENTRYPOINT. For a proper container init system.

>TODO: source or execute repo script?

I referenced some functions in my build.sh - we may need them in the Makefile approach too.

**Comment by zokradonh** [comment]
> TODO get actual version from container, below fails since it runs through dumb-init

dumb-init should not interfere with this.

**Comment by fbartels** [comment]
> dumb-init should not interfere with this.

Indeed that did fail because of something else. Todo was already obsolete, though I have removed it now.

> I use it in both images as ENTRYPOINT. For a proper container init system.

Ok, will need to read up how dumb-init works then.

**Comment by fbartels** [comment]
resolved by https://github.com/zokradonh/kopano-docker/pull/13
