### ISSUE TITLE
performance tip: instead of relying on http sockets (and ssl client certs) mount /run/kopano in containers

### ISSUE THREAD

**Issue by fbartels** [zokradonh/kopano-docker#12]
Hi,

one thing that I just saw while going through your compose file. You could simplify your setup and increase performance (file sockets have a higher throughput than going through http(s)) by just mounting the same /run/kopano across all containers.

**Comment by zokradonh** [comment]
Ok, thank you. This is something that clearly need to be changed. This design decision is from my early docker phase and I have never touched it since then.

**Comment by fbartels** [comment]
fixed through #14
