### ISSUE TITLE
Can't set insecure_cookies anymore

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [zokradonh/kopano-docker#139]
I am running this stack in a fresh environment using the today's latest images. Due to my earlier proposed reverse proxy setup, i try to set the insecure_cookies flag for the webapp. But this does seem to be currently broken.

I am using the following kopano_webapp.env:
```
KCCONF_WEBAPP_INSECURE_COOKIES=true
KCCONF_WEBAPP_CLIENT_TIMEOUT=3600
KCCONF_WEBAPPPLUGIN_MDM_PLUGIN_MDM_USER_DEFAULT_ENABLE_MDM=true
```
The log of the container looks fine:
```
kopano_webapp            | Kopano WebApp is using the default: connection
kopano_webapp            | Configuring Kopano WebApp for use behind a reverse proxy
kopano_webapp            | Setting INSECURE_COOKIES = true in /etc/kopano/webapp/config.php
kopano_webapp            | boolean value
kopano_webapp            | Setting CLIENT_TIMEOUT = 3600 in /etc/kopano/webapp/config.php
kopano_webapp            | Setting INSECURE_COOKIES = "true" in /etc/kopano/webapp/config.php
kopano_webapp            | Setting PLUGIN_MDM_SERVER_SSL = false in /etc/kopano/webapp/config-mdm.php
kopano_webapp            | boolean value
kopano_webapp            | Setting PLUGIN_MDM_USER_DEFAULT_ENABLE_MDM = true in /etc/kopano/webapp/config-mdm.php
kopano_webapp            | boolean value
kopano_webapp            | Ensure config ownership
kopano_webapp            | Starting Apache
```

But everything except the insecure cookies are set correctly:
```
docker-compose exec kopano_webapp cat /etc/kopano/webapp/config.php | grep INSECURE_COOKIES
        define("INSECURE_COOKIES", false);
```
```
docker-compose exec kopano_webapp cat /etc/kopano/webapp/config.php | grep TIMEOUT
        define('CLIENT_TIMEOUT', '3600');
```
```
docker-compose exec kopano_webapp cat /etc/kopano/webapp/config-mdm.php
<?php
        define('PLUGIN_MDM_USER_DEFAULT_ENABLE_MDM', true);
define('PLUGIN_MDM_SERVER', 'localhost');
define('PLUGIN_MDM_SERVER_SSL', false);
?>
```

Did i miss something or is the php config patch system broken?

**Comment by fbartels** [comment]
Hi @cguentherTUChemnitz,

for whatever reason the sed command does not seem to match the insecure_cookies line and since with kweb it still works I did not notice this yet. 

PS: as you can see from the startup log insecure cookies is already set in the container startup and is not needed to set through an env. but as kweb works with an unmodified setting I am inclined to remove this from start.sh.

**Comment by fbartels** [comment]
ah yes of course... https://github.com/zokradonh/kopano-docker/commit/48e22da9d17ab6ae658be98d0997f226924fcacb

hooray for inconsistent quoting in the webapp configuration....
