### ISSUE TITLE
not able to pull non-demo ldap image

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [zokradonh/kopano-docker#154]
The stack starts fine with: `LDAP_CONTAINER=kopano_ldap_demo` in the .env. When changing to `LDAP_CONTAINER=kopano_ldap` i get:
```
Pulling ldap (zokradonh/kopano_ldap:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling ldap (zokradonh/kopano_ldap:)...
ERROR: pull access denied for zokradonh/kopano_ldap, repository does not exist or may require 'docker login'
```

Is this desired behavior that the non-demo open-ldap image is behind an login, whereas the demo version is public available?

**Comment by fbartels** [comment]
> Is this desired behavior that the non-demo open-ldap image is behind an login, whereas the demo version is public available?

That sounds like a good idea. I have to think about it :-D

Actually the image was just missing in the ´make publish´ target. this is fixed now.

**Comment by cguentherTUChemnitz** [comment]
Thanks a lot for your fast fix.
