### ISSUE TITLE
update Docker hub description from Travis

### ISSUE THREAD

**Issue by fbartels** [zokradonh/kopano-docker#179]
dockercloud CI sets the hub.docker.com image description, thats the reason I have this automated build still on. Normal `docker push` does not set it.

Though, since some month it's possible to set it externally by this:
https://stackoverflow.com/a/55082686/1431178

Maybe we should implement this and disable dockercloud CI completely.

_Originally posted by @zokradonh in https://github.com/zokradonh/kopano-docker/pull/177#issuecomment-501493128_

**Comment by zokradonh** [comment]
> Do you want to work on this or shall I give it a try?

I am currently very busy. I would appreciate your work on this topic.

Since those features are generally needed by all people using docker with travis it would be good to outsource it from this repository.

**Comment by zokradonh** [comment]
Actually, maybe I will make a golang CLI for this. Good practice work for go language..

**Comment by fbartels** [comment]
Maybe it could be a good addition for https://github.com/genuinetools/reg. But I am not quite sure if this is in the scope of the tool.
