### ISSUE TITLE
Issue login kopano-docker

### ISSUE THREAD

**Issue by rikirenz** [zokradonh/kopano-docker#207]
Hey Guys,

After I ran this command:
```
$ docker-compose up
```
when I try to access the url: `https://localhost/webapp/`
This is what I get:
![image](https://user-images.githubusercontent.com/4679712/61794938-96955180-ae22-11e9-9863-dce61faf2e91.png)

As you can see there are no login fields. Do you have any idea about this strange behaviour?

Thanks,
Riccardo

**Comment by fbartels** [comment]
Hi @rikirenz,

depending on when you last pulled in changes WebApp could be waiting in Konnect for login (change was in https://github.com/zokradonh/kopano-docker/commit/d4c8b57b60783a64ac2cca3152a399f0c129db8d). Not quite sure though if that will work with "localhost".

**Comment by fbartels** [comment]
Closing since there was no response from initial reporter.
