### ISSUE TITLE
Cleanup ldap demo data

### ISSUE THREAD

**Issue by fbartels** [zokradonh/kopano-docker#23]
After users have been synced the following message is logged:

```
kopano_server | Mon Nov 12 21:45:45 2018: [error  ] Not all objects in relation found for object "sales"
kopano_server | Mon Nov 12 21:45:45 2018: [error  ] Not all objects in relation found for object "dutch-users"
kopano_server | Mon Nov 12 21:45:45 2018: [error  ] Not all objects in relation found for object "groep1"
```

There must be must be an obsolete reference in the ldap import.

**Comment by nupplaphil** [comment]
I already created a small LDAP image which creates a full LDAP tree based on environment variables.

Look here:
https://github.com/nupplaphil/kopano-ldap/tree/initial_docker/docker

I can add it per PR to this repo if wanted

**Comment by fbartels** [comment]
Hi, it seems we have chosen a similar base for our ldap efforts. I do like the possibility to have some demo users in the ldap. Do you think you can integrate this easily into your pr (e.g. have a default env to import demo users)?

**Comment by nupplaphil** [comment]
I'm believing that docker images should be build for out-of-the-box productive environment usage. Therefore I don't think that having demo-data in an image is best practice for docker images.

Normally you have something like an `.example` directory to store such demo-data and their usage.

If I'd see a "kopano/ldap" image. I'd like to include it in my docker environment and start it with my domain.
=> And I got 3 demo-users as well without wanting them.

**Comment by fbartels** [comment]
> If I'd see a "kopano/ldap" image. I'd like to include it in my docker environment and start it with my domain.

Yes, that was my main reason for not pushing this image to the  registry and instead making a local build out of it. 

I would expect from most production environments that they anyways already have a working ldap that they want to use instead.

**Comment by nupplaphil** [comment]
Ah I understand your point of view :-)

This is right for companies, but not for "private nerds" as I am. I know from nextcloud or similar other open source projects that they deliver some kind of out-of-the-box environments for private usage as well.

But it's not a problem if you/we don't like it in this repository. I can make a fork of the ldap directory and create a docker-hub-image based on the latest changes of this repository :-)

**Comment by fbartels** [comment]
Maybe as a result out of this the readme could make it clearer that the bundled ldap is optional and how to modify the git repo to remove the demo users?

**Comment by nupplaphil** [comment]
hm .. Sorry for hijacking this issue. Shall I open a new one? :-(

I think the ldap image isn't usable for companies, because - as you said - they are using their own ldap environment and it isn't usable for private persons, because of the demo data.

So if a private person wants to use a full-blown mailserver, it has to adapt the ldap-image before using it. Maybe we can adapt the `Makefile` to make an ldap test environment and an ldap production environment. I think we should service the ldap image as easy as possible so everybody can use it nearly out-of-the-box :-)

So I'd rather prefer  to adapt the README to explain how to add a demo-data-set if wanted (`make build-test` ?)

[edit]
f.e.:
- `zokradonh/kopano-ldap:prod` and  `zokradonh/kopano-ldap:latest` without demo-data
- `zokradonh/kopano-ldap:test` or  `zokradonh/kopano-ldap:dev` with demo-data

**Comment by fbartels** [comment]
yes, since the original cause for this issue has been resolved a dedicated topic would probably be better. Alternatively you could also open a pr, since I do not generally disagree with your proposal. I would suggest the following workflow.

I do see this here primarily for demo and evaluation purposes, as already written in the readme:

> This repository contains an easy to replicate recipe to spin up a Kopano demo enviroment, which can (through modification of .env and possibly docker-compose.yml) also be used for production environments.

What I could imagine:
- replace current (local) ldap image with your proposed image (no users, configurable through env)
- add another ldap-demo image which uses the above as a base and adds the demo ldif
- use ldap-demo by default in docker-compose (still as a local build)
- have "kopano-ldap" optionally in compose as well, but commented by default
- bonus: setup.sh could ask if one wants to use the demo ldap or start with an empty one (defaults to demo)

This then still needs some updates to the readme to make clear what to change to get an empty ldap.

Sounds good?
