### ISSUE TITLE
hexdump: command not found

### ISSUE THREAD

**Issue by cnoork** [zokradonh/kopano-docker#247]
After starting the ./setup.sh on my synology 918+ DSM 6.2.2-24922 Update 2 I get after a view question:   "./setup.sh: line 10: hexdump: command not found"

I can't find the file on my NAS only in a view containers.

How can I add hexdump or what should I do to get a workaround?

With kind regards,
Chris

**Comment by fbartels** [comment]
Hi @cnoork,

the Synology os is a bit bare bones for some tasks. If it's only about the setup script then you could check if there is an alternative to generate a password string that would also work for Synology.

But as soon as you want to build your own containers you need a few more utilities as well. When doing tests the last time I created https://github.com/zokradonh/kopano-docker/tree/master/build to get all required build tools.

**Comment by fbartels** [comment]
@cnoork if you want to open a pr to replace hexdump in the setup script then https://gist.github.com/earthgecko/3089509 gives some pointers on generating password strings.

**Comment by cnoork** [comment]
Thnx for the explanation, I have now changed the setup line with "hexdump" to the following lines which makes it now also working for Synology:

```
if [ -n "`which hexdump`" ]
then
   hexdump -n 16 -v -e '/1 "%02X"' /dev/urandom
elif [ -n "`which fold`" ]
then
   cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1
else
   hexdump
fi
```

**Comment by fbartels** [comment]
Hi @cnoork,

thanks for sharing your code.I would say that it would be enough for `setup.sh` to just replace the current `hexdump` command with the `cat` command from your elif.

Do you want to make a pr for this so that this change is accredited to your user?

One note though, the else in your above code would lead to the script hanging indefinitly as hexdump expects some form of input.

**Comment by cnoork** [comment]
Hi fbartels, my goal would be that every Synology user could install Kopano directly with minimal adjustments. The reason to do the else with that command is to make sure the script will exit. I could by the way say the setup script was now successful running but there are now another things to look at. I need to figure out about which port, network and container is needed. Not yet that far that I understand which choices I need to make. Maybe I need to start a new discussion for installing Kopano on Synology with Intel processor. I can't imagine that there are not more people interested or even have it working....

**Comment by fbartels** [comment]
> The reason to do the else with that command is to make sure the script will exit

but then you probably want to have an `exit 1` in the else instead.

> my goal would be that every Synology user could install Kopano directly

In case you are unaware there is already a project building a Kopano app for Synology at https://github.com/TosoBoso/Kopano4s

**Comment by cnoork** [comment]
Hi @fbartels,

Yes indeed exit 1 is an better solution. Thnx for the tip to look at TosoBoso. I will look how that one will work.
