### ISSUE TITLE
set more kopano server config varables as Docker enviroment variables

### ISSUE THREAD

**Issue by XtraLarge** [zokradonh/kopano-docker#262]
Hi,
in my usecase I must set the kopano server parameter "ATTACHMENT_STORAGE = files".

I've tried to set "KCCONF_SERVER_ATTACHMENT_STORAGE = files" but nothing happens inside the container. 

Did I made a mistake? or are the docker environment variables set fixed?

If the second is true, it would be a great and more flexible enhancement to make docker environment prefixes that set the server parameter after the prefix for the respective service config in the container?

**Comment by fbartels** [comment]
Hi @XtraLarge,

handling of configuration options is explained in https://github.com/zokradonh/kopano-docker/tree/master/core. If that does not work then most probably you are setting the environment variable wrong, but a bug is of course also possible.

edit: works for me `kopano_server       | 2019-10-18T11:38:27.070175: [error  ] Attachments are stored with option "files_v2", but "files" is selected.`

**Comment by XtraLarge** [comment]
Hi,

I've found the problem there was a blank before and after the "=". 

This did not work ;)
