### ISSUE TITLE
Adding a CLI for LDAP

### ISSUE THREAD

**Issue by nupplaphil** [zokradonh/kopano-docker#28]
Because I want to have everything under control in the docker-container, I'm currently writing a `kopano-ld` CLI (written in go), which will be able to control the LDAP entries just like the `kopano-cli` for DB backends.

Maybe we can integrate it into the LDAP docker image

It can be found at https://github.com/nupplaphil/kopano-ldap (It's not ready yet, I'm working on it)

**Comment by fbartels** [comment]
I like that idea

**Comment by fbartels** [comment]
Closing here for the moment.
