### ISSUE TITLE
Make use of kopano-spamd for automated ham/spam learning

### ISSUE THREAD

**Issue by mithomas** [zokradonh/kopano-docker#280]
Since a couple of releases, Kopano includes a `kopano-spamd`-package to handle automated learning of ham/spam messages - yet it is notably absent here :-).

From what I have understand about the setup of the images, I would therefore propose a new spamd-image based on the core-image (with respective extension to `start-service.sh` and a named volume to export the mails to.

Complementary, there probably should be a new docker image for `inotify-spamlearn` watching this named volume and triggering SpamAssassin learning via `spamc` - this way it is transparent whether SA where SA actually runs (be it the included mail image, a dedicated container or even the host system for not fully containerized environments).

What do you think?

**Comment by fbartels** [comment]
Hi @mithomas,

yes, your plan sounds good. One addition would be that it does not need (or should not be) a dedicated image for spamd, instead you can just install the package in the kopano_core container and then extend the existing start-service script (like you already said).

given that spamd just exports messages adding another service that then forwards/processes these message seems like a good idea as well.
