### ISSUE TITLE
Making official kopano images

### ISSUE THREAD

**Issue by nupplaphil** [zokradonh/kopano-docker#29]
If we **really** want to make this images official, here are the requirements:
https://github.com/docker-library/official-images/blob/master/NEW-IMAGE-CHECKLIST.md

But than we have to restructure the way, how this repo is working.
- creating Docker images with `build` scripts (maybe with different architectures?)
- moving the `docker-compose.yml` to - f.e. - an `.example` directory for quick setups
- creating CI like #26 already mentioned
- And last but not least we need support of the official `kopano.io` upstream/associated

**Comment by nupplaphil** [comment]
I already created this sort of docker image for `Friendica` -> https://github.com/friendica/docker so if you want I can help you. Just in case we want to even go this way :-)

**Comment by fbartels** [comment]
That idea sounds intriguing. I do not see any other mail related images in the official library, though. 

I'd say lets first get the orchestration going and worry about building from the ground up later.

PS: another goal would be for this to become "Kopano recommended/supported docker images". This is something I am pushing for at the moment.

**Comment by cguentherTUChemnitz** [comment]
@fbartels I want to use this channel to thank you alot to push kopano into the docker world with official support. I think this is very beneficial for kopano to gain a lot of momentum. You can address a lot of people testing with images directly from dockerhub. Small and young companies, as well as privat nerds are using docker as a modern hosting platform. Even when there is no need for cluster management. Providing your great groupware with a modern mailstack and ldap setup is in my eyes the last missing point of the dockerization of the entire internal it-infrastructure using open-source solutions.

When your image reaches dockerhub with this great and easily modifiable example modification, i will spread the word to let everyone interested in this topic test your groupware stack.

**Comment by fbartels** [comment]
Thanks @cguentherTUChemnitz 

> When your image reaches dockerhub

The images are already there, so spread the word and bring in feedback and possible contributors ;-)
