### ISSUE TITLE
ERROR: Invalid interpolation format for "environment" option in service "web": "FQDN=${FQDNCLEANED?err}"

### ISSUE THREAD

**Issue by theoneandonly-vector** [zokradonh/kopano-docker#315]
I'm using a fresh Ubuntu 18.04.3 -installation and I get the following error:
ERROR: Invalid interpolation format for "environment" option in service "web": "FQDN=${FQDNCLEANED?err}"

right after I try to start it using 
docker-compose up -d

**Comment by theoneandonly-vector** [comment]
kopano_webapp.env has 0 lines when I open it up using nano.

**Comment by fbartels** [comment]
Hi @theoneandonly-vector,

`kopano_webapp.env` being empty is normal, the setup script creates them empty in case you want to add additional environment variables through it (docker-compose would complain if the file is missing).

As for the error message. can you post the information from https://github.com/zokradonh/kopano-docker#troubleshooting?

**Comment by theoneandonly-vector** [comment]
Hey there

oh, thx :)

the error message produced when running docker-compose up:
ERROR: Invalid interpolation format for "environment" option in service "web": "FQDN=${FQDNCLEANED?err}"

the output of docker-compose ps:
ERROR: Invalid interpolation format for "environment" option in service "web": "FQDN=${FQDNCLEANED?err}"

for failed containers the output of docker-compose logs $containername:
can't see a container when using:
docker ps -a

the contents of your .env:
# please consult https://github.com/zokradonh/kopano-docker
# for possible configuration values and their impact
CORE_VERSION=latest
WEBAPP_VERSION=latest
ZPUSH_VERSION=latest
KONNECT_VERSION=latest
KWM_VERSION=latest
MEET_VERSION=latest
KDAV_VERSION=latest

LDAP_CONTAINER=
LDAP_ORGANISATION="ORGNAME"
LDAP_DOMAIN=mail.ORGNAME.tld
LDAP_BASE_DN=dc=ORGNAME,dc=tld
LDAP_SERVER=ldap://10.255.255.2:7389
LDAP_ADMIN_PASSWORD=
LDAP_READONLY_USER_PASSWORD=*******
LDAP_BIND_DN=cn=ubuntudockerhost,cn=memberserver,cn=computers,dc=ORGNAME,dc=tld
LDAP_BIND_PW=******
LDAP_SEARCH_BASE=dc=neutronix,dc=ch

# LDAP query filters
LDAP_QUERY_FILTER_USER=(&(kopanoAccount=1)(mail=%s))
LDAP_QUERY_FILTER_GROUP=(&(objectclass=kopano-group)(mail=%s))
LDAP_QUERY_FILTER_ALIAS=(&(kopanoAccount=1)(kopanoAliases=%s))
LDAP_QUERY_FILTER_DOMAIN=(&(|(mail=*@%s)(kopanoAliases=*@%s)))
SASLAUTHD_LDAP_FILTER=(&(kopanoAccount=1)(uid=%s))

# LDAP user password self-service reset settings
SELF_SERVICE_SECRETEKEY=**********************
SELF_SERVICE_PASSWORD_MIN_LENGTH=5
SELF_SERVICE_PASSWORD_MAX_LENGTH=0
SELF_SERVICE_PASSWORD_MIN_LOWERCASE=0
SELF_SERVICE_PASSWORD_MIN_UPPERCASE=0
SELF_SERVICE_PASSWORD_MIN_DIGIT=1
SELF_SERVICE_PASSWORD_MIN_SPECIAL=1

# switch the value of these two variables to use the activedirectory configuration
KCUNCOMMENT_LDAP_1=!include /usr/share/kopano/ldap.openldap.cfg
KCCOMMENT_LDAP_1=!include /usr/share/kopano/ldap.active-directory.cfg

MYSQL_HOST=db
MYSQL_ROOT_PASSWORD=************************
MYSQL_USER=kopano
MYSQL_PASSWORD=***************************
MYSQL_DATABASE=kopano

KCCONF_SERVER_SERVER_NAME=Kopano

POSTMASTER_ADDRESS=postmaster@ORGNAME.tld
MAILBOXLANG=de_CH.UTF-8
TZ=Europe/Zurich

# Defines how Kopano can be accessed from the outside world
FQDN=mail.ORGNAME.tld
FQDNCLEANED=mail.ORGNAME.tld
DEFAULTREDIRECT=/webapp
EMAIL=info@ORGNAME.tld
CADDY=2015
HTTP=80
HTTPS=443
LDAPPORT=389
SMTPPORT=25
SMTPSPORT=465
MSAPORT=587
IMAPPORT=143
ICALPORT=8080
KOPANOPORT=236
KOPANOSPORT=237

# Settings for test environments
INSECURE=no

# Docker and docker-compose settings
# Docker Repository to push to/pull from
docker_repo=zokradonh
COMPOSE_PROJECT_NAME=kopano
COMPOSE_FILE=docker-compose.yml:docker-compose.ports.yml

# Modify below to build a different version, than the kopano nightly release
#KOPANO_CORE_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/core:/final/Debian_9.0/
#KOPANO_MEET_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/meet:/final/Debian_9.0/
#KOPANO_WEBAPP_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/webapp:/final/Debian_9.0/
#KOPANO_WEBAPP_FILES_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/files:/final/Debian_9.0/
#KOPANO_WEBAPP_MDM_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/mdm:/final/Debian_9.0/
#KOPANO_WEBAPP_SMIME_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/smime:/final/Debian_9.0/
CADDY=2015
HTTP=80
HTTPS=443
LDAPPORT=389
SMTPPORT=25
SMTPSPORT=465
MSAPORT=587
IMAPPORT=143
ICALPORT=8080
KOPANOPORT=236
KOPANOSPORT=237

# Settings for test environments
INSECURE=no

# Docker and docker-compose settings
# Docker Repository to push to/pull from
docker_repo=zokradonh
COMPOSE_PROJECT_NAME=kopano
COMPOSE_FILE=docker-compose.yml:docker-compose.ports.yml

# Modify below to build a different version, than the kopano nightly release
#KOPANO_CORE_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/core:/final/Debian_9.0/
#KOPANO_MEET_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/meet:/final/Debian_9.0/
#KOPANO_WEBAPP_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/webapp:/final/Debian_9.0/
#KOPANO_WEBAPP_FILES_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/files:/final/Debian_9.0/
#KOPANO_WEBAPP_MDM_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/mdm:/final/Debian_9.0/
#KOPANO_WEBAPP_SMIME_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/smime:/final/Debian_9.0/
#KOPANO_ZPUSH_REPOSITORY_URL=http://repo.z-hub.io/z-push:/final/Debian_9.0/
#RELEASE_KEY_DOWNLOAD=1
#DOWNLOAD_COMMUNITY_PACKAGES=0

# Additional packages to install
ADDITIONAL_KOPANO_PACKAGES=""
ADDITIONAL_KOPANO_WEBAPP_PLUGINS="kopano-webapp-plugin-spell kopano-webapp-plugin-spell-de-ch kopano-webapp-plugin$

the output of docker-compose config:
ERROR: Invalid interpolation format for "environment" option in service "web": "FQDN=${FQDNCLEANED?err}"

**Comment by fbartels** [comment]
The does look ok, though. can you also post the output of `docker-compose -v`? It sounds like you don't have the minimal required versions (first bullet of https://github.com/zokradonh/kopano-docker#how-to-get-started).

**Comment by theoneandonly-vector** [comment]
docker-compose version 1.17.1, build unknown

**Comment by theoneandonly-vector** [comment]
I see.. that seems to be to old.. I just installed it from ubuntu's repo's..

**Comment by theoneandonly-vector** [comment]
after I installed the correct versions I get:
ERROR: The Compose file is invalid because:
Service ldap has neither an image nor a build context specified. At least one must be provided.

I removed the LDAP-part from the docker.compose.yml, do I need to change something else?

**Comment by theoneandonly-vector** [comment]
quick Summary:
I've installed the wrong Docker and docker-compose -Version.
