### ISSUE TITLE
ERROR: The Compose file is invalid because: Service ldap has neither an image nor a build context specified. At least one must be provided.

### ISSUE THREAD

**Issue by theoneandonly-vector** [zokradonh/kopano-docker#316]
**Describe the bug**
running "docker-compose up -d" after setup inside the project-folder. shows me the following error:
ERROR: The Compose file is invalid because: Service ldap has neither an image nor a build context specified. At least one must be provided.

**To Reproduce**
install  Ubuntu 18.04.3 LTS
install Docker version 19.03.5
install docker-compose version 1.25.1

**Expected behavior**
Docker should start-up all the containers (everything but LDAP) for me.

**Additional context**
I removed all entrys from "ldap:" inside "docker-compose.yml" (everything between " - ${FQDNCLEANED?err}" and "mail:"

I removed the ldap.env -file.

docker-compose ps:
ERROR: The Compose file is invalid because:
Service ldap has neither an image nor a build context specified. At least one must be provided.

docker-compose config
ERROR: The Compose file is invalid because:
Service ldap has neither an image nor a build context specified. At least one must be provided.

the contents of your .env:

please consult https://github.com/zokradonh/kopano-docker
for possible configuration values and their impact
CORE_VERSION=latest
WEBAPP_VERSION=latest
ZPUSH_VERSION=latest
KONNECT_VERSION=latest
KWM_VERSION=latest
MEET_VERSION=latest
KDAV_VERSION=latest

LDAP_CONTAINER=
LDAP_ORGANISATION="ORGNAME"
LDAP_DOMAIN=mail.ORGNAME.tld
LDAP_BASE_DN=dc=ORGNAME,dc=tld
LDAP_SERVER=ldap://10.255.255.2:7389
LDAP_ADMIN_PASSWORD=
LDAP_READONLY_USER_PASSWORD=*******
LDAP_BIND_DN=cn=ubuntudockerhost,cn=memberserver,cn=computers,dc=ORGNAME,dc=tld
LDAP_BIND_PW=******
LDAP_SEARCH_BASE=dc=ORGNAME,dc=tld

LDAP query filters
LDAP_QUERY_FILTER_USER=(&(kopanoAccount=1)(mail=%s))
LDAP_QUERY_FILTER_GROUP=(&(objectclass=kopano-group)(mail=%s))
LDAP_QUERY_FILTER_ALIAS=(&(kopanoAccount=1)(kopanoAliases=%s))
LDAP_QUERY_FILTER_DOMAIN=(&(|(mail=@%s)(kopanoAliases=@%s)))
SASLAUTHD_LDAP_FILTER=(&(kopanoAccount=1)(uid=%s))

LDAP user password self-service reset settings
SELF_SERVICE_SECRETEKEY=**********************
SELF_SERVICE_PASSWORD_MIN_LENGTH=5
SELF_SERVICE_PASSWORD_MAX_LENGTH=0
SELF_SERVICE_PASSWORD_MIN_LOWERCASE=0
SELF_SERVICE_PASSWORD_MIN_UPPERCASE=0
SELF_SERVICE_PASSWORD_MIN_DIGIT=1
SELF_SERVICE_PASSWORD_MIN_SPECIAL=1

switch the value of these two variables to use the activedirectory configuration
KCUNCOMMENT_LDAP_1=!include /usr/share/kopano/ldap.openldap.cfg
KCCOMMENT_LDAP_1=!include /usr/share/kopano/ldap.active-directory.cfg

MYSQL_HOST=db
MYSQL_ROOT_PASSWORD=************************
MYSQL_USER=kopano
MYSQL_PASSWORD=***************************
MYSQL_DATABASE=kopano

KCCONF_SERVER_SERVER_NAME=Kopano

POSTMASTER_ADDRESS=postmaster@ORGNAME.tld
MAILBOXLANG=de_CH.UTF-8
TZ=Europe/Zurich

Defines how Kopano can be accessed from the outside world
FQDN=mail.ORGNAME.tld
FQDNCLEANED=mail.ORGNAME.tld
DEFAULTREDIRECT=/webapp
EMAIL=info@ORGNAME.tld
CADDY=2015
HTTP=80
HTTPS=443
LDAPPORT=389
SMTPPORT=25
SMTPSPORT=465
MSAPORT=587
IMAPPORT=143
ICALPORT=8080
KOPANOPORT=236
KOPANOSPORT=237

Settings for test environments
INSECURE=no

Docker and docker-compose settings
Docker Repository to push to/pull from
docker_repo=zokradonh
COMPOSE_PROJECT_NAME=kopano
COMPOSE_FILE=docker-compose.yml:docker-compose.ports.yml

Modify below to build a different version, than the kopano nightly release
#KOPANO_CORE_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/core:/final/Debian_9.0/
#KOPANO_MEET_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/meet:/final/Debian_9.0/
#KOPANO_WEBAPP_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/webapp:/final/Debian_9.0/
#KOPANO_WEBAPP_FILES_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/files:/final/Debian_9.0/
#KOPANO_WEBAPP_MDM_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/mdm:/final/Debian_9.0/
#KOPANO_WEBAPP_SMIME_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/smime:/final/Debian_9.0/
CADDY=2015
HTTP=80
HTTPS=443
LDAPPORT=389
SMTPPORT=25
SMTPSPORT=465
MSAPORT=587
IMAPPORT=143
ICALPORT=8080
KOPANOPORT=236
KOPANOSPORT=237

Settings for test environments
INSECURE=no

Docker and docker-compose settings
Docker Repository to push to/pull from
docker_repo=zokradonh
COMPOSE_PROJECT_NAME=kopano
COMPOSE_FILE=docker-compose.yml:docker-compose.ports.yml

Modify below to build a different version, than the kopano nightly release
#KOPANO_CORE_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/core:/final/Debian_9.0/
#KOPANO_MEET_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/meet:/final/Debian_9.0/
#KOPANO_WEBAPP_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/webapp:/final/Debian_9.0/
#KOPANO_WEBAPP_FILES_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/files:/final/Debian_9.0/
#KOPANO_WEBAPP_MDM_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/mdm:/final/Debian_9.0/
#KOPANO_WEBAPP_SMIME_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/smime:/final/Debian_9.0/
#KOPANO_ZPUSH_REPOSITORY_URL=http://repo.z-hub.io/z-push:/final/Debian_9.0/
#RELEASE_KEY_DOWNLOAD=1
#DOWNLOAD_COMMUNITY_PACKAGES=0

Additional packages to install
ADDITIONAL_KOPANO_PACKAGES=""
ADDITIONAL_KOPANO_WEBAPP_PLUGINS="kopano-webapp-plugin-spell kopano-webapp-plugin-spell-de-ch kopano-webapp-plugin$

the output of docker-compose config:
ERROR: Invalid interpolation format for "environment" option in service "web": "FQDN=${FQDNCLEANED?err}"

**Comment by fbartels** [comment]
Hi @theoneandonly-vector,

its not enough to simply remove the ldap entry from `docker-compose.yml` since the container is referenced as a dependency from other containers. For example at: https://github.com/zokradonh/kopano-docker/blob/5a4335998d8edfd73cbf8a2a1c1fb615b8a3585f/docker-compose.yml#L54-L55

I would also not recommend to modify the compose file directly as this will cut your off from easy updates to it in the future (you have to merge changes and potentially resolve conflicts yourself), you should rather put your modifications into an override file. See https://github.com/zokradonh/kopano-docker#additional-configuration--need-to-adjust-any-values-after-the-initial-run-of-setupsh for more information. 

Edit: Look at https://github.com/zokradonh/kopano-docker/blob/master/examples/docker-compose.override.yml-disable-mail for an example on how to disable the standard mail container. the same approach should work for the ldap container as well.

**Comment by theoneandonly-vector** [comment]
Hi @fbartels thank you very much for pointing this out :)

I had to remove the "depends: -ldap" manually, as the override-file can't remove this. I only used it like your example to disable ldap without removing it's configuration in the docker-compose.yml

sadly I'm still not able to get it running..:
Creating kopano_mail ...
Creating kopano_web_1             ... error
Creating kopano_kopano_ssl_1 ...
Creating kopano_ldap         ...
Creating kopano_kopano_kustomer_1 ...
Creating kopano_db                ...

Creating kopano_kopano_kustomer_1 ... error
 mkdir /var/lib/dbus/machine-id: read-only file system
Creating kopano_mail              ... done
ERROR: for kopano_kopano_kustomer_1  Cannot start service kopano_kustomer: error while creating mount source path '/vCreating kopano_kopano_ssl_1      ... done

ERROR: for kopano_ldap  Cannot start service ldap: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"--loglevel\": executable file not found in $PATH": unknown

ERROR: for web  Cannot start service web: error while creating mount source path '/var/lib/dbus/machine-id': mkdir /var/lib/dbus/machine-id: read-only file system

ERROR: for kopano_kustomer  Cannot start service kopano_kustomer: error while creating mount source path '/var/lib/dbus/machine-id': mkdir /var/lib/dbus/machine-id: read-only file system

ERROR: for ldap  Cannot start service ldap: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"--loglevel\": executable file not found in $PATH": unknown
ERROR: Encountered errors while bringing up the project.
nx@mail:/opt/kopano-docker$

**Comment by theoneandonly-vector** [comment]
I had to remove the "depends: -ldap" manually, as the override-file can't remove this. I only used it like your example to disable ldap without removing it's configuration in the docker-compose.yml

**Comment by fbartels** [comment]
This does not really sound like you actually removed the ldap image 

> Creating kopano_ldap ...
> [..]
> ERROR: for kopano_ldap Cannot start service ldap: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: "--loglevel": executable file not found in $PATH": unknown

To really know what is going on here you would need to post your docker-compose file (e.g. through `docker-compose config`.

PS: when posting large snippets it always helps with readability when formatting them. Github is using markdown for this, but there are also buttons for it above the editor.

**Comment by fbartels** [comment]
this should be easier now with #319
