### ISSUE TITLE
HrLogon server "default:" user "SYSTEM": network error 2020-01-27 00:05:52,944 - backup - WARNING - could not connect to server at 'default:', retrying in 5 sec

### ISSUE THREAD

**Issue by theoneandonly-vector** [zokradonh/kopano-docker#327]
when I run the following command:
docker run --rm -it -v /var/run/kopano/:/var/run/kopano -v $(pwd):/kopano/path zokradonh/kopano_utils kopano-backup

I get:
HrLogon server "default:" user "SYSTEM": network error 2020-01-27 00:05:52,944 - backup - WARNING - could not connect to server at 'default:', retrying in 5 sec

do I need to configure anything for this command to work?

**Comment by fbartels** [comment]
Hi @theoneandonly-vector,

if you do not pass a specific server to kopano-backup then it tries to connect to the local unix socket at `/var/run/kopano/server.sock`. But for you a socket does not exist at this location. 

There is also a kopano-backup example tailored to the docker-compose environment at https://github.com/zokradonh/kopano-docker/blob/0277a5e27acf9cdf4a5f8d2a5255b6acd54aa838/docker-compose.yml#L465.

**Comment by theoneandonly-vector** [comment]
thank you very much for pointing this out

**Comment by theoneandonly-vector** [comment]
this works, but the two commands in the descirption do not. I also don't get it yet on how to do this for other commands..

**these won't work for me (getting the error):**

> Run a kopano-backup: docker run --rm -it -v /var/run/kopano/:/var/run/kopano -v $(pwd):/kopano/path zokradonh/kopano_utils kopano-backup


**a working version of this one would be nice, so I can just go in there and then use all the kopano-commands..:**

> Get a shell in a new container to (for example) run kopano-migration-pst: docker run --rm -it -v /var/run/kopano/:/var/run/kopano -v $(pwd):/kopano/path zokradonh/kopano_utils (to directly run kopano-migration-pst just append it to the command)

**Comment by fbartels** [comment]
> but the two commands in the descirption do not

there are way more than just two commands in the readme. you'd have to be more specific. lastly it also depends on the environment.

The commands at https://github.com/zokradonh/kopano-docker#some-more-commands-for-those-unfamiliar-with-docker-compose are just meant as examples and are not copy/paste how-tos. But if you want to run a command in a running container you just have to go a few lines higher:

> Run commands in a running container: docker-compose exec kopano_server kopano-cli --list-users

**Comment by theoneandonly-vector** [comment]
is there a command which will put me inside "kopano_utils" and allows me to use all of the opano utils..?

**Comment by fbartels** [comment]
That's basically already in my second reply:

`docker run --rm -it --volumes-from kopano_server -v /root/kopano-backup:/kopano/path zokradonh/kopano_utils:latest bash`
