### ISSUE TITLE
Automatic image builds

### ISSUE THREAD

**Issue by nupplaphil** [zokradonh/kopano-docker#33]
As far as I can see, we push new docker images with
https://github.com/zokradonh/kopano-docker/blob/8b20e1151f2f8a26e1b6b3c1c3503b0e2e660868/Makefile#L77-L104

I'd rather suggest to use https://docs.docker.com/docker-hub/builds/ instead of manually executing the builds.

- It's a native docker hub functionality
- We don't need any custom Makefiles for it
- We can add the automation just for tags f.e. or trigger it with ever PR merge
- We can map every sub-directory (`core`, `webapp`, `ldap`, ...) to a specific automatic build

The only thing we need is a repository on docker hub with automatic build enabled

**Comment by fbartels** [comment]
Hi, automatic builds are already enabled for example in https://hub.docker.com/r/zokradonh/kopano_core/.

The makefile is primarily meat if one wants to push to a custom repo or build images with supported packages.
