### ISSUE TITLE
how to correctly set the langauge in .env so I don't need to modify the docker itself.

### ISSUE THREAD

**Issue by theoneandonly-vector** [zokradonh/kopano-docker#330]
I get the problem that new users get an english store.
I set the entry "MAILBOXLANG=de_DE.UTF-8" inside ".env"

changing the store manually using "kopano-storeadm -D -n username@domain.tld && kopano-storeadm -C -l de_DE.UTF-8 -n username@domain.tld" works.

**Comment by fbartels** [comment]
Ah yes, that seems to be a side effect of moving out configuration files from `/etc/kopano` to `/tmp/kopano` (to facilitate running the container mostly read-only). When now running `kopano-admin` or `kopano-cli` it does not see the language setting.

One would need to call either of these programs with the --config option and point it to `/tmp/kopano/admin.cfg`.

I'll have to think further for a more generalised solution and would appreciate pull requests.
