### ISSUE TITLE
SMTP submission not working

### ISSUE THREAD

**Issue by theoneandonly-vector** [zokradonh/kopano-docker#334]
there seems to be no way of sending email via SMTP from this server.

I tried using ports:
25
465
587
with no encryption, STARTTLS, TLS.

**Comment by fbartels** [comment]
Hi @theoneandonly-vector,

this project uses https://github.com/tomav/docker-mailserver for the mta component. If you want to use SMTP submission I'd recommend to read up in their documentation.
