### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by theoneandonly-vector** [zokradonh/kopano-docker#335]
Web-Part already uses a Let's Encrypt-Certificate, but is there a way to use them for imaps and smtps to? 

I only found the following:
https://github.com/zokradonh/kopano-docker/issues/136
https://github.com/zokradonh/kopano-docker/issues/16

but didn't get how it works now..

**Comment by fbartels** [comment]
Hi @theoneandonly-vector,

the two tickets you have linked were closed because of inactivity, not because what they described was implemented.

Being able to connect Pop3/IMAP clients is not important to me personally so I have not invested time into it. If someone else wants to adapt the compose file for it I'll gladly review and merge it.

**Comment by theoneandonly-vector** [comment]
there seem to be an issue with the mail-docker:
https://github.com/tomav/docker-mailserver/issues/1369

**Comment by theoneandonly-vector** [comment]
running this inside the mail-docker-container and restarting it works for me (re-using the cert which is used by kopano-web):
mkdir -p /etc/postfix/ssl
                        cp "$SSL_CERT_PATH" /etc/postfix/ssl/cert
                        cp "$SSL_KEY_PATH" /etc/postfix/ssl/key
                        chmod 600 /etc/postfix/ssl/cert
                        chmod 600 /etc/postfix/ssl/key

now we only need to create a crontask to automatically refresh it.

**Comment by theoneandonly-vector** [comment]
so I use this now:

crontab -e
0 0 1 * * /opt/kopano-docker/thisrunsonceamonth.sh

thisrunsonceamonth.sh:
docker exec -it kopano_mail bash -l -c 'mkdir -p /etc/postfix/ssl && cp "$SSL_CERT_PATH" /etc/postfix/ssl/cert && cp "$SSL_KEY_PATH" /etc/postfix/ssl/key && chmod 600 /etc/postfix/ssl/cert && chmod 600 /etc/postfix/ssl/key'
