### ISSUE TITLE
performance: use php-fpm instead of mod_php in web containers

### ISSUE THREAD

**Issue by fbartels** [zokradonh/kopano-docker#36]
- [x] webapp
- [x] z-push
- [ ] kdav

**Comment by nupplaphil** [comment]
Nice idea.

Do you mean to switch `webapp` and `zpush` to a php-fpm container?
If so we do need the `kweb` container for serving assets because php-fpm cannot do it, don't we?

I'm just curious :-)

**Comment by fbartels** [comment]
I do not know yet how, but given that fpm performs way better than mod_php it's a good idea to switch this. In the past I've seen quite some images that bundle php-fpm and a Webserver in one image, but that is also not the 100% solution. I still need to see.

**Comment by fbartels** [comment]
The changes for webapp have been deployed a while ago, would still need to be done for z-push and kdav.
