### ISSUE TITLE
Getting started without demo users

### ISSUE THREAD

**Issue by aksdb** [zokradonh/kopano-docker#363]
When setting up the containers without pre-populating the LDAP store with users, I'm at a loss at how to actually get started. The official Kopano documentation focuses on local stores or require an already existing LDAP with users managed via AD or similar mechanisms.

How is kopano-docker intended to be setup when you don't want to start with demo users? (i.e. preparing a production setup for example) How do I get my initial admin account? My user accounts?

**Comment by fbartels** [comment]
Hi @aksdb,

that largely depends on your actual environment.

This project main goal (for me and also documented in the readme) is a demo environment, but from this demo environment its not very far into an actual productions deployment (although in that case I would not recommend to use the Kopano nightlies, but instead use the bundled Makefile to build containers based on the supported Kopano releases).

The setup script already asks if you want to use an empty ldap tree or the one with demo users. The empty ldap tree already has the kopano ldap schema imported so you could just use your ldap management utility of choice (this projects bundles both phpldapadmin and ldap account manager as examples, although to have Kopano templates in the latter you need to but the pro version).

If you already have your own ldap tree, then you need to remove docker-compose.ldap.yml from the started files and configure kopano_server to connect to your actual ldap.

Ldap configuration for Kopano is explained in https://documentation.kopano.io/kopanocore_administrator_manual/configure_kc_components.html

**Comment by aksdb** [comment]
Ah I didn't notice the ldap-extra package. That helped :-)
Thanks for the infos :-)
