### ISSUE TITLE
Can't find kopano_kapps

### ISSUE THREAD

**Issue by Chris-Frank** [zokradonh/kopano-docker#402]
Doccker-compose up throws an error during the inital pull. 
![error](https://user-images.githubusercontent.com/17689712/83137649-d20b4700-a0e9-11ea-85ca-457b6b682e7e.png)

**Comment by fbartels** [comment]
ah yes, indeed. When adding the container there was no publish setup in the Makefile added for it. This is fixed with the above pr.
