### ISSUE TITLE
alternative address not working

### ISSUE THREAD

**Issue by theoneandonly-vector** [zokradonh/kopano-docker#408]
**Describe the bug**
the following entry:
KCCONF_LDAP_LDAP_EMAILALIASES_ATTRIBUTE=MAILALTERNATIVEADDRESS
won't add a mailbox to my user when a mail-address is specified on my user at this attribute.

**To Reproduce**
write:
KCCONF_LDAP_LDAP_EMAILALIASES_ATTRIBUTE=MAILALTERNATIVEADDRESS
inside "kopano_server.env"

**Expected behavior**
I want to receive e-mails on a second mail-address.

**Comment by fbartels** [comment]
Hi @theoneandonly-vector,

can you explain a bit more what you mean with:

> won't add a mailbox to my user

Having an alias does not mean that there will be another mailbox for the user, the user will simply have another address that will deliver to the same mailbox.

**Comment by theoneandonly-vector** [comment]
this isn't working right now:
"the user will simply have another address that will deliver to the same mailbox"

so I want this:
"Expected behavior
I want to receive e-mails on a second mail-address."

**Comment by fbartels** [comment]
I just gave this a quick try on my local system. user1 has in addition to this own address also two aliases:

```
SMTP:user1@kopano.demo
smtp:Jonas@kopano.demo
smtp:Jonas.Brekke@kopano.demo
```
(`user1@kopano.demo` is his main address, the other two are aliases)

I've sent a mail to `Jonas@kopano.demo` and the mail was delivered for the user.

**Comment by theoneandonly-vector** [comment]
I changed the wrong field. As I am using Univention it won't be the field under "Mail" but under "Contact"
