### ISSUE TITLE
change messagesize-limit

### ISSUE THREAD

**Issue by theoneandonly-vector** [zokradonh/kopano-docker#409]
how to change message_size_limit

I set:
POSTFIX_MESSAGE_SIZE_LIMIT=20971520

but I still get:
552 5.3.4 Message size exceeds fixed limit
when sending just 10mb

**Comment by fbartels** [comment]
Hi @theoneandonly-vector,

this project uses https://github.com/tomav/docker-mailserver for the mta part. For questions regarding this I would recommend to ask in their issue tracker.
