### ISSUE TITLE
Z-Push container missing php-xml

### ISSUE THREAD

**Issue by engelant** [zokradonh/kopano-docker#410]
As stated in the title a dependency for z-push is missing and therefor autodiscover won't work
```
Sat Jun 13 00:42:01 2020 "POST /autodiscover/autodiscover.xml HTTP/1.1" 500 - "-" "Android-Mail/2020.05.17.313130477.Release"
13/06/2020 00:42:01 [   58] [ INFO] [#unknown] Z-Push version='2.5.2+0-0'
[Sat Jun 13 00:42:01.826052 2020] [php7:error] [pid 58] [client x.x.x.x:57608] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /usr/share/z-push/autodiscover/autodiscover.php:157
Stack trace:
	#0 /usr/share/z-push/autodiscover/autodiscover.php(84): ZPushAutodiscover->getIncomingXml()
	#1 /usr/share/z-push/autodiscover/autodiscover.php(68): ZPushAutodiscover->DoAutodiscover()
	#2 /usr/share/z-push/autodiscover/autodiscover.php(387): ZPushAutodiscover::DoZPushAutodiscover()
	#3 {main}
	thrown in /usr/share/z-push/autodiscover/autodiscover.php on line 157
```

By making the contaianer rw I could confirm the following fixes it.
```console
apt update
apt install php-xml -y
apachectl -k restart
```

**Comment by fbartels** [comment]
Hi @engelant,

yes that seems reasonable. I would recommend to report this issue with Z-Push directly -> https://jira.z-hub.io/projects/ZP/issues/

For a workaround we could temporarily install the package manually.

**Comment by engelant** [comment]
@fbartels I don't quite get it, is `simplexml_load_string()` not supposed to be used any more?
I was thinking of adding `php-xml` around [here](https://github.com/zokradonh/kopano-docker/blob/4effa19d91a779508261d4b9e3e4f277d010ead0/zpush/Dockerfile#L54).

**Comment by fbartels** [comment]
I am not a php developer so I don't know of the downsides of this functionality.

Agree with the place to add, you linked to the exact line where a package is already installed for a similar reason.
