### ISSUE TITLE
z-push default configuration mismatch

### ISSUE THREAD

**Issue by engelant** [zokradonh/kopano-docker#411]
With the default docker configuration there is an inconsistency of the config between `autodiscover.conf.php` and `z-push.conf.php`. Assuming the default OOBE behaviour is a single domain configuration, the file `z-push.conf.php` needs this line changed
`define('USE_FULLEMAIL_FOR_LOGIN', false);`
which can again be accomplished by adding this to `kopano_zpush.env`
`KCCONF_ZPUSH_USE_FULLEMAIL_FOR_LOGIN=false`

However, I suppose it would be best to make it default for new installations by adding it to the defaults of the setup routine, so it won't break existing installations. This misaligned defaults seems to come directly from  [z-push repo](https://github.com/Z-Hub/Z-Push).

**Comment by fbartels** [comment]
The reasoning behind having this value set to true can be found in:

- https://github.com/Z-Hub/Z-Push/commit/4c6e1bafa5f1e40c1581fc171da30b6d572156f9
- https://jira.z-hub.io/browse/ZP-772

**Comment by engelant** [comment]
But wouldn't that mean [this](https://github.com/Z-Hub/Z-Push/blob/2ef5fa77543492948b035522f4ecbc4a94956dad/src/autodiscover/config.php#L46) should then also be set true?

**Comment by fbartels** [comment]
I think it could. Has been a while since I last set it up.

**Comment by engelant** [comment]
Let me throw in another point of view:
With the default installation using OpenLDAP and the test users, one creates a domain with an self selected domain/suffix. After the setup one can login to kopano via */webapp* with only the username e.g. **user1** instead of the full username. In terms of consistency I would argue, that same should go for z-push, at least for the default setup. Again, pointing out that the "default installation" seems to represent a single domain installation.
Or to put it differently: why does the default login format between z-push and webapp differ?

**Comment by fbartels** [comment]
> In terms of consistency I would argue, that same should go for z-push, at least for the default setup.

Yes, but that already works with the default configuration. But I agree that just based on the name of the configuration option that may not be intuitive.
