### ISSUE TITLE
container gateway is started from unmodified config

### ISSUE THREAD

**Issue by engelant** [zokradonh/kopano-docker#412]
It seems that the configuration for the kopano gateway is updated/configured but then not used.
```console
kopano-gateway --help
Usage:

kopano-gateway [-h|--host <serverpath>] [-c|--config <configfile>]
  -h path       Use alternate connect path (e.g. file:///var/run/socket).
                Default: file:///var/run/kopano/server.sock
  -V Print version info.
  -c filename   Use alternate config file (e.g. /etc/kopano-gateway.cfg)
                Default: /etc/kopano/gateway.cfg
```

It seems that there is no -F switch and the alternate config file should be set to `-c /tmp/kopano/gateway.cfg` [here](https://github.com/zokradonh/kopano-docker/blob/4effa19d91a779508261d4b9e3e4f277d010ead0/core/start-service.sh#L157).

**Comment by fbartels** [comment]
Please see https://github.com/zokradonh/kopano-docker/pull/414#issuecomment-643813313

**Comment by engelant** [comment]
Sorry, my bad, didn't realize `KOPANO_CONFIG_PATH` took care of that.
I guess I assumend the config not getting red as `STARTTLS` on IMAP wasn't working, allthough I set CA and KEY. While I found out, that the actual issue was I needed to enable `imaps_listen=0.0.0.0:993` for STARTTLS on 143 to work, I assumed my "config fix" was part of the chain.

**Comment by theoneandonly-vector** [comment]
> 

hey there, where exactly do you put the modded kopano-gateway.cfg on the host?

**Comment by engelant** [comment]
No modded config, just set a few env variables in the kopano_gateway.env.
```
KCCONF_GATEWAY_DISABLE_PLAINTEXT_AUTH=yes
KCCONF_GATEWAY_SSL_PRIVATE_KEY_FILE=/server/ssl/example.com.key
KCCONF_GATEWAY_SSL_CERTIFICATE_FILE=/server/ssl/fullchain.cer
KCCONF_GATEWAY_SERVER_HOSTNAME=example.com
KCCONF_GATEWAY_IMAP_PUBLIC_FOLDERS=no
KCCONF_GATEWAY_IMAPS_LISTEN=0.0.0.0:993
```
