### ISSUE TITLE
how to use the new calendar?

### ISSUE THREAD

**Issue by theoneandonly-vector** [zokradonh/kopano-docker#417]
how can I test / use the new calendar mentioned here:

https://github.com/zokradonh/kopano-docker/commit/4e2060e4915975b42bae2c59f2cab6140965983c

**Comment by fbartels** [comment]
You can access it at https://FQDN/calendar

**Comment by theoneandonly-vector** [comment]
thx, is there a new roadmap? as the old ones I found are outdated.

**Comment by fbartels** [comment]
No, I don't think there is a public roadmap when it comes to the calendar. If you are a Kopano partner I recommend reaching out to the Kopano sales team if you need one for on of your customers.
