### ISSUE TITLE
Latest kopano_zpush docker image failed to build with Dockerfile

### ISSUE THREAD

**Issue by vadonka** [zokradonh/kopano-docker#430]
**Describe the bug**
When i try to use the kopano/kopano_zpush image with Dockerfile i got this error message:
mv: cannot move 'core-10.0.6.406.e263d46-Debian_10-amd64' to 'core/core-10.0.6.406.e263d46-Debian_10-amd64': Directory not empty
ERROR: Service 'zpush' failed to build: The command '/bin/bash -o pipefail -c . /kopano/helper/create-kopano-repo.sh &&     if [ ${DOWNLOAD_COMMUNITY_PACKAGES} -eq 1 ]; then         dl_and_package_community "core" "$DOWNLOAD_DISTRIBUTION" "$DOWNLOAD_CHANNEL" "$DOWNLOAD_BRANCH";     fi' returned a non-zero code: 1

**To Reproduce**
Just use with a simple Dockerfile
FROM zokradonh/kopano_zpush

This was fine before the yesterday pull, and its working with the 2.5.1 tag too. Only this image is affected:
sha256:3bb7b2d3ae488f6bd849964c2bdb38ab15ee9d54343fdc2e0fc3c6cb434e189c

**Comment by fbartels** [comment]
I had some follow-up questions in https://forum.kopano.io/topic/3337/latest-kopano-kopano_zpush-docker-image-failed-to-build. But it seems like you are not actually building the image in your own, but using it as a base for your own, did I get that right?
