### ISSUE TITLE
kopano_kapps is bound to CORE_VERSION

### ISSUE THREAD

**Issue by engelant** [zokradonh/kopano-docker#435]
As there seems to be an LDAP related bug with the latest kopano core nightly, I wanted to downgrade kopano_core by updating `CORE_VERSION=10.0.6.13` in my *.env* file.
This leads to kopano_kapps being unable to resolve the docker image, as there is no `zokradonh/kopano_kapps:10.0.6.357`.

I would suggest to change
```
  kopano_kapps:
    image: ${docker_repo:-zokradonh}/kopano_kapps:${KAPPS_VERSION:-latest}
```
and add `KAPPS_VERSION=latest` to the *.env* generator script.

**Comment by fbartels** [comment]
Hi @engelant,

thanks for opening up an issue. That is indeed an oversight.

Your steps sound good to me, a PR would be most welcome.

**Comment by fbartels** [comment]
Thanks @engelant. I made a small style fix as the test suite was failing because of it. The pr has now been merged.

**Comment by engelant** [comment]
No idea what went wrong there. I literally just copy pasted the block in nano.

**Comment by fbartels** [comment]
Don't worry about it. Copy pasting switched tabs to spaces.
