### ISSUE TITLE
LDAP demo ldif is using {{ LDAP_DOMAIN }} replacment which is not supported

### ISSUE THREAD

**Issue by longsleep** [zokradonh/kopano-docker#45]
The used ldap image https://github.com/osixia/docker-openldap#seed-ldap-database-with-ldif is supporting only a few replacements for the ldif seed files. LDAP_DOMAIN is not one of them, thus this stays unreplaced in LDAP resulting in invalid email addresses.

To be clear:
```
mail: user2@{{ LDAP_DOMAIN }}
```

Is what ends up in ldap without getting replaced.

**Comment by longsleep** [comment]
Relevant code is at https://github.com/osixia/docker-openldap/blob/stable/image/service/slapd/startup.sh#L69 - best action is probably to propose a change to upstream ldap image so LDAP_DOMAIN is also replaced in ldif seeds.

**Comment by fbartels** [comment]
Hi @longsleep ,

thanks for the hint and the reference to the upstream code.  Let's see if the upstream source would be interested in this change.

**Comment by nupplaphil** [comment]
Ah damn.. Was my mistake.. I l've the fear, I tested with the wrong branch.

I'm looking for it

**Comment by fbartels** [comment]
@nupplaphil no worries. I fixed it for the time being.

**Comment by nupplaphil** [comment]
Thanks!! :)
