### ISSUE TITLE
Dynamic config.php from env broken

### ISSUE THREAD

**Issue by engelant** [zokradonh/kopano-docker#452]
2bc513f4fc638412d7562508f2e27693bf7f3f3b breaks my setup, as /tmp/webapp/config.php inside kopano_webapp container isn't updated (sed doesn't match any more with the additional \x27).

As this is part of the base php container I don't know where else it would break or fix something.

**Comment by fbartels** [comment]
Ah, yes. It seems I remembered it the wrong way, webapp switched to all double quotes not to all single quotes.

**Comment by engelant** [comment]
Nice, thank you.

**Comment by engelant** [comment]
actually there is a typo, fix in #454

**Comment by XtraLarge** [comment]
With your hint I stopped the stacked with `docker-compose down` and deleted all images with the cmmand `docker system prune -a`. After that it seemed to work!
