### ISSUE TITLE
Webapp Insecure Cookie

### ISSUE THREAD

**Issue by XtraLarge** [zokradonh/kopano-docker#455]
Hi,

sorry that I previously wrote in german, so now in english.

My question is ...
Could it be that since the last changes a little bug exists?

In my kopano webapp.env file exists a long time before the rows:
```
KCCONF_WEBAPP_INSECURE_COOKIES=true
KCCONF_WEBAPPPLUGIN_MDM_PLUGIN_MDM_USER_DEFAULT_ENABLE_MDM=true
KCCONF_WEBAPPPLUGIN_MDM_PLUGIN_MDM_SERVER=kopano_zpush:9080
```
Everything was fine before, but since the last restart of the conatainer there were the following part in the file /tmp/webapp/config.php of the container : ...
```
 // Set to 'true' to disable secure session cookies and to allow log-in without HTTPS.
        define("INSECURE_COOKIES", false);
```

**Comment by fbartels** [comment]
Please post your questions and problems in english.

The issue you are describing was initially reported in https://github.com/zokradonh/kopano-docker/issues/452 and has since then been fixed already.
