### ISSUE TITLE
KCCONF_WEBAPP_INSECURE_COOKIES won't be set

### ISSUE THREAD

**Issue by XtraLarge** [zokradonh/kopano-docker#459]
Hi,

sorry, i did not find a way to reopen my previous question, but I think it must be a bug.

First of all I will thank you for you patience and you great work for this app, so thanx a lot! 

Now the my problem ...

In my kopano webapp.env file exists a long time before the rows:
```
KCCONF_WEBAPP_INSECURE_COOKIES=true
KCCONF_WEBAPPPLUGIN_MDM_PLUGIN_MDM_USER_DEFAULT_ENABLE_MDM=true
KCCONF_WEBAPPPLUGIN_MDM_PLUGIN_MDM_SERVER=kopano_zpush:9080
```

Everything was fine before, but since the last restart of the conatainer there were the following part in the file /tmp/webapp/config.php of the container : ...
```
 // Set to 'true' to disable secure session cookies and to allow log-in without HTTPS.
        define("INSECURE_COOKIES", false);
```
and In the logfile I saw the line: "Setting INSECURE_COOKIES = true in /tmp/webapp/config.php"

You wrote in a previous question that this happend because of a bug with the quotes, so I've tried to change the line in the kopano webapp.env to:
`KCCONF_WEBAPP_INSECURE_COOKIES="true"`

the result in the the file /tmp/webapp/config.php of the container was : ...
```
 // Set to 'true' to disable secure session cookies and to allow log-in without HTTPS.
        define("INSECURE_COOKIES", ""true"");
```

**Comment by fbartels** [comment]
Hi @XtraLarge, the case I was referring to in #455 was #452. The quoting is not in the environment variable itself, but in the quoting in the script that is run at container startup. You need to pull the latest container for the setting to be set properly.

**Comment by XtraLarge** [comment]
With your hint I stopped the stacked with `docker-compose down` and deleted all images with the cmmand `docker system prune -a`. After that it seemed to work!

**Comment by fbartels** [comment]
you could've also run `docker-compose pull && docker-compose up -d`
