### ISSUE TITLE
identifier for variable in config-file

### ISSUE THREAD

**Issue by XtraLarge** [zokradonh/kopano-docker#461]
Hello,

in an other question you asked me how you could document the use of the varibles so that other user better understand them ....

I think it would be great to have a list which variable-prefix configures which config-file.

Something like:
KCCONF_ZPUSHAUTODISCOVER_... = autodiscover-config.php
KCCONF_WEBAPP_... = config.php
KCCONF_WEBAPPPLUGIN_MDM_PLUGIN_... = config-mdm.php

Every time I need anouther file, I begins to tryout. :(

**Comment by fbartels** [comment]
Yes I guess the description given at https://github.com/zokradonh/kopano-docker/tree/master/php#configuration-through-environment-variables could be extended with a list of all possible configuration files (and maybe some commands to get possible config file values and configuration options?).

The linked block could also be added to the readme in the zpush folder.

For the z-push container you can find the known mappings at https://github.com/zokradonh/kopano-docker/blob/master/zpush/start.sh#L88

Please open a pr
