### ISSUE TITLE
Disable SSL between kopano services

### ISSUE THREAD

**Issue by nupplaphil** [zokradonh/kopano-docker#47]
The current services are bound together inside a own (encrypted) network segment.

Do we really need the self-signed certificates for communicating inside this network? I think we just need it for the web-connected services (f.e. `web`).

It's just an idea, based on a discussion with others about this topic :-)

What do you think?

**Comment by fbartels** [comment]
I think the current compose file only uses file sockets or plain http sockets. 

The SSL certificates are a nice to have, though. 

SSL is in regards to the Kopano architecture not required to communicate securely, but to perform authentication. E.g. kopano-dagent needs to authenticate with kopano-server to be allowed to deliver mails into a users mailbox.

**Comment by niklastojts** [comment]
I am also interested in the purpose of the volume mount kopanossl/:/kopano/ssl on containers. I do prefer secure communication between containers. Users out there creates all kinds of networks, not always the simple bridge so encrypted communication is good. Is security the purpose or is it required for kopano to work? Self-signed certificate will always be enough here? I see sharing of kopano sockets so I can not understand why self-signed certificates everywhere?

I would like to see kopanossl be mounted as read only when it is not supposed to be written to. It makes is easier for me as a administrator to understand the docker-compose file and increases security a little bit.
like:
```
    volumes:
      - kopanodata/:/kopano/data:rw
      - kopanossl/:/kopano/ssl:ro
      - kopanosocket/:/run/kopano:rw
```

**Comment by fbartels** [comment]
> I would like to see kopanossl be mounted as read only

You are invited to open a pr for this.

>Is security the purpose or is it required for kopano to work? Self-signed certificate will always be enough here? I see sharing of kopano sockets so I can not understand why self-signed certificates everywhere?

That part is still there, because before the compose file uses a mount to share the socket between containers, containers actually used a http connection for communication. the ssl certificates are still in the script, since you (if you want to) could still use http(s) to link the containers. 

Self signing is not problem for kopano here, since the ca that these certificates are signed with are also known to kopano.

**Comment by fbartels** [comment]
Closing since the original question had been answered.
