### ISSUE TITLE
INSECURE_COOKIES in webapp seems to not work again

### ISSUE THREAD

**Issue by engelant** [zokradonh/kopano-docker#474]
It seems that with a recent version the config.php.dist has changed, not containing
**define("INSECURE_COOKIES", false);**
any more.
I manually tried (with a copy of config.php.dist)
`php_cfg_gen config2.php INSECURE_COOKIES true`
Which results in
```
Setting INSECURE_COOKIES = true in config2.php
WARNING: Config option INSECURE_COOKIES not found in config2.php! You may have misspelled the confing setting.
```
And furthermore just appends the setting to the config file in a wrong manner like so:
```
...
?>
define('INSECURE_COOKIES', 'true');
```

**Comment by engelant** [comment]
Nevermind, it's **SECURE_COOKIES=false** now

**Comment by fbartels** [comment]
Yes, the webapp team recently tried to unify some naming conventions for config options. There was an announcement on the Kopano forum.
