### ISSUE TITLE
After some time I can't authenticate against IMAP anymore.

### ISSUE THREAD

**Issue by theoneandonly-vector** [zokradonh/kopano-docker#475]
**Describe the bug**
After some time I can't authenticate against IMAP anymore.

**To Reproduce**
use IMAP for a few days.

**Expected behavior**
IMAP let me authenticate.

**Additional context**
docker logs -f kopano_kopano_gateway_1:
```
[kopano-gateway|T6] [error  ] Unable to accept(): Too many open files
[kopano-gateway|T6] [error  ] Unable to accept IMAP socket connection: network error (80040115)
```

when I check using "ss" I have many "CLOSE-WAIT" connections on IMAP.

**Comment by fbartels** [comment]
Hi @theoneandonly-vector,

this seems to be an error in the software and not specific to Docker. For debugging it would be helpful to know with which version you have initially encountered this and which version you are currently running.

The same error has been reported at https://forum.kopano.io/topic/3594/gateway-server-handling-connection-problem, please post your input there.
