### ISSUE TITLE
New build/test pipeline

### ISSUE THREAD

**Issue by zokradonh** [zokradonh/kopano-docker#483]
Travis Build changed to paid
Docker Hub Build changes to paid

Where to build this project in the future?
- GitHub Workflows?
-  ..

@fbartels Do you plan something with Kopano already or do we need a solution here?

**Comment by fbartels** [comment]
Hi @zokradonh,

I think since this is hosted on Github I personally would use Github Actions for CI. But overall this project does sadly not have enough users/traction so that I can commit my time to setting it up.
