### ISSUE TITLE
Update to Kopano Konnect 0.34 please

### ISSUE THREAD

**Issue by jnweiger** [zokradonh/kopano-docker#490]
The latest version at dockerhub seems to be 0.33.11 -- we identified an issue with token refresh of native clients in 
https://github.com/owncloud/client/issues/9056#issuecomment-922363069

Please prepare a new docker release wiht that fix.

**Comment by fbartels** [comment]
Hi @jnweiger,

a new container for Konnect has been pushed.

https://hub.docker.com/layers/197214613/kopano/kopano_konnect/0.34.0/images/sha256-f16908fdf228a2162ef47ebdd4879b625c5bede617b96b26212d340e6fc65fbe?context=repo

**Comment by jnweiger** [comment]
Confirmed. latest now brings me 0.34.0
:green_heart: 
Thank you!
