### ISSUE TITLE
Using local DNS

### ISSUE THREAD

**Issue by nupplaphil** [zokradonh/kopano-docker#52]
I know from https://github.com/mailcow/mailcow-dockerized that they use a local DNS because of the high amount of DNS requests (to not get blacklisted).

Do you know if this is a topic for kopano/mailserver?
If so, do we want to have local DNS too?

f.e. this is one https://github.com/mailcow/mailcow-dockerized/tree/master/data/Dockerfiles/unbound

**Comment by fbartels** [comment]
No, I cannot think of a component which would do many external dns lookups (besides the postfix part). When using smime you could have some requests for the oscp part, but I think this is all client side.

**Comment by nupplaphil** [comment]
OK. I did a little bit research and found out that it originally wasn't for the amount of DNS requests, it was for DNSSEC too:
https://github.com/mailcow/mailcow-dockerized/commit/b367ec0ace533ee3f32bd16c70a5e7f7ab52f571#diff-4e5e90c6228fd48698d074241c2ba760

**Comment by fbartels** [comment]
Ok, closing since all mail flow related parts are handled by https://github.com/tomav/docker-mailserver

**Comment by nupplaphil** [comment]
I think we do have to rethink about the local DNS.
Because otherwise some of the DNS-Blacklist lookups aren't working.

Look here
https://www.spamhaus.org/faq/section/DNSBL%2520Usage#261
> If you are using a free "open DNS resolver" service such as the Google Public DNS (8.8.8.8) and others [...] to resolve your DNSBL requests, in most cases you will receive a "not listed" (NXDOMAIN) reply from Spamhaus' public DNSBL servers

https://github.com/tomav/docker-mailserver/issues/948

> If you're using Google's public DNS servers (or several other public DNS servers) they don't allow querying of DNSBL. You can use the new Cloudflare DNS 1.1.1.1 or 1.0.0.1
> 
> I started working on a companion container that would run Unbound but since Cloudflare released their DNS servers, I gave up.

f.e.:
```shell
mail_1            | Dec 22 22:20:07 mail postfix/dnsblog[2764]: warning: dnsblog_query: lookup error for DNS query 158.10.213.190.list.dnswl.org: Host or domain name not found. Name service error for name=158.10.213.190.list.dnswl.org type=A: Host not found, try again
mail_1            | Dec 22 22:20:07 mail postfix/dnsblog[2766]: warning: dnsblog_query: lookup error for DNS query 158.10.213.190.zen.spamhaus.org: Host or domain name not found. Name service error for name=158.10.213.190.zen.spamhaus.org type=A: Host not found, try again
```

**Comment by fbartels** [comment]
The linked issue makes the following suggestion:

> You can add the following to your docker-compose.yml to fix this:
> 
> services:
  mail:
    image: ...
    ...
    dns: 1.1.1.1

Seems easy enough to include this, although it feels like it should be something else than cloudflare if this project should make a DNS recommendation.

**Comment by nupplaphil** [comment]
At least we should add a warning to the README that in case somebody wants to use DNSBL , we use a public DNS IP for it.

But you're right that adding the dns was the pretty easiest way to solve it ;-)
