### ISSUE TITLE
Adding kdav image

### ISSUE THREAD

**Issue by nupplaphil** [zokradonh/kopano-docker#54]
I found
https://github.com/Kopano-dev/kdav
when searching for a proper caldav/cardav integration in kopano.

It seems really good and I'd like to integrate it in the docker image world.

As far as I can see it's "pure" PHP so I'd like to make it based on the `php:apache` image and adding the sabre / phplogging dependencies with `docker-php-ext-configure` if necessary.

An example on what it might look at the end is
https://github.com/friendica/docker/blob/master/Dockerfile-debian.template
(but without the template fields and so on ;-) )

I'll create it in the `kdev` directory.

Do we need the `ical` after this transition anymore? It seems they serve the same service, don't they?

**Comment by nupplaphil** [comment]
btw. we would be able to create a pure `php-fpm` image too, which will be a good first step for #36
[edit] and that would be no effort to switch between php-fpm / apache if we base on the `php` image :-)

**Comment by fbartels** [comment]
Yes, i would like to add it as well. I actually already started playing with it yesterday (see https://github.com/fbartels/kopano-docker/tree/kdav for the WIP).

Yes, this could be a potential replacement for kopano-ical, but keep in mind that it has not been formally released so there may (or will) be stuff that will not work as good as the current implementation.

I have not yet looked at your proposed base image, the thing that could make it hard to use is that for kdav to work (same counts for WebApp and Z-Push) php-mapi is needed.

**Comment by nupplaphil** [comment]
Ah, I see .. So we have to add the kopano repositories and therefore should use the base image. That's a little bit sad, I saw a chance to create a base image for multi-based images (php:fpm, php:apache, php:fpm-alpine) on different plattforms (amd64, x86, ..). As a first base for "official" kopano images :-). .. But Nevermind. 

So I'll wait for your work to finish I guess. Because parallel working doesn't seems good for me :-)
