### ISSUE TITLE
Wrong LDAP_QUERY_FILTER_DOMAIN

### ISSUE THREAD

**Issue by nupplaphil** [zokradonh/kopano-docker#56]
https://github.com/zokradonh/kopano-docker/blob/78d4c60f6ed7d9b1ba107277b2f3300ae24c59ff/setup.sh#L209

Should be
```
LDAP_QUERY_FILTER_DOMAIN=(&(|(mail=*@%s)(kopanoAliases=*@%s)))
```

Otherwise aliases are not working.

**Comment by fbartels** [comment]
Thanks
