### ISSUE TITLE
Add HEALTHCHECKs for some services

### ISSUE THREAD

**Issue by zokradonh** [zokradonh/kopano-docker#6]
- [ ] server
- [ ] dagent
- [ ] spooler
- [ ] gateway
- [ ] search
- [ ] webapp

**Comment by fbartels** [comment]
#14 added the healthcheck to the Dockerfile, but its not doing anything at the moment.

**Comment by fbartels** [comment]
With https://github.com/zokradonh/kopano-docker/pull/223 there are now some (still basic) checks
