### ISSUE TITLE
switch from docker automated builds to builds coming from travis

### ISSUE THREAD

**Issue by fbartels** [zokradonh/kopano-docker#63]
- [x] travis.yml needs some tuning to only run ´make publish´ in the master branch
- [x] optimize runtime of makefile to not evaluate component_version before the container is actually built
- [x] create travis account
- [x] add travis badge in readme

**Comment by nupplaphil** [comment]
Just a suggestion how I solve this task:

https://github.com/friendica/docker/blob/master/.travis.yml

**Comment by fbartels** [comment]
With https://github.com/zokradonh/kopano-docker/commit/a0e045ff383663631874989cdb017f854e9a9453 (and the following fixup commits) there is now a travis file that builds, tags and pushes builds into the docker hub. The current secret env variables are there to push builds from the kopano-dev github repo into the kopano docker organisation. appropriate secrets could/should be added to the travis file to push to the original docker hub account as well.

**Comment by zokradonh** [comment]
Unfortunately the Docker Hub readme is only automatically refreshed on docker hub automatic build. This is something that also needs to be solved.

Maybe by keeping the automatic build on docker hub on...

**Comment by fbartels** [comment]
@zokradonh yes, that sadly seems to be the case. I looked through the documentation and while you can get the description from an image in the registry through a webhook, there does not seem to be a way to set it in an automated fashion outside of an automated build.

Since you have added the badge (and seemingly added secrets to your travis account). all tasks of this ticket have been resolved and therefore I am closing here.
