### ISSUE TITLE
make webmeetings available

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [zokradonh/kopano-docker#64]
The current state of the setup.sh enables the usage of a lot of webapp plugins. Nevertheless, the usage of the webmeetings seems not to be available in the current state of the setup.sh as well as the docker-compose.yml configuration. Are there any plans to integrate this feature soon?

**Comment by fbartels** [comment]
Hi,

I personally have no plans for integrating the old Webmeetings into this project. The spreed based software will soon be replaced with a rewrite based on the new Kopano Rest API, OpenID Connect and a PWA webclient. 

For the latter I have already started integration the rest API in a branch. This still needs some more touches, though.

If anyone else wants to integrate the old Webmeetings pull requests are welcome.

**Comment by cguentherTUChemnitz** [comment]
Okay thanks for your fast and insightful reply. I don't want to boilerplate this repo with outdated stuff. So i am fine with closing this ticket and waiting for the webmeetings replacement.

best,
Christian
