### ISSUE TITLE
Misleading build.sh command synopsis regarding networkname

### ISSUE THREAD

**Issue by mithomas** [zokradonh/kopano-docker#7]
While the command synopsis for `build.sh` reads:

```
# ./build.sh 
Usage: build.sh -c core|webapp [-s serial] [-b master|final|pre-final] [-p buildcontext] [-n networkname] [[-a buildarg] ...] [-i]
Example: build.sh -c core -s ABC123456789DEF -b final
-i   Do not use cache on docker build.
-b   If no branch is specified, 'master' will be built by default.
-p   If no buildcontext is specified, it will be built from git repository. Normally, you do not need to specify this.
-n   If no networkname is specified, it will create and use a network named 'buildproxy_net'.
-a   You can specify custom build args via e.g. -a KOPANO_CORE_REPOSITORY_URL=http://thisismy/url -a KOPANO_WEBAPP_REPOSITORY_URL=http://thisismy/url.
```

and thus claiming networkname to be optional even in the example, running `# ./build.sh  -c core -b final -a TEST` yields:

```
Start building kopano core image version (newest)...
Sending build context to Docker daemon  20.48kB
Step 1/21 : FROM debian:stretch
 ---> 3bbb526d2608
Step 2/21 : LABEL maintainer=az@zok.xyz       version="2.0"
 ---> Using cache
 ---> 87ec05cbbcb0
Step 3/21 : RUN mkdir -p /kopano/repo /kopano/data
 ---> Running in ae472068a71b
network buildproxy_net not found
```

**Comment by zokradonh** [comment]
Yes, you are right. There is a bug. Maybe something like `-n host` will workaround it for now. But I have no time to test it right now.

As long as there is no serial specified the script will not try to create the network, which is wrong. I need to fix it.

Another workaround would be to create the network manually by `docker network create --attachable buildproxy_net`

**Comment by mithomas** [comment]
No worries - `-n host` does indeed work around it. (If there would be something like a priority field, this one would be low.)

**Comment by zokradonh** [comment]
Due to simplification of build.sh there is no build-network necessary anymore.
