### ISSUE TITLE
Add Minio for S3 attachments to example compose file?

### ISSUE THREAD

**Issue by fbartels** [zokradonh/kopano-docker#74]
Kopano-server is capable of storing attachments in S3. Should the example compose file make use of this?

**Comment by cguentherTUChemnitz** [comment]
I would love to see that the default is completely on-premise and leaves the storage solution decision to the administrator. In my mind, the more often solution of storing to S3 is that the administrator uses docker storage volume drivers to store directly to S3 where the application does not have to handle this. Regarding to this:
https://docs.docker.com/compose/compose-file/#driver
https://docs.docker.com/registry/storage-drivers/s3/

**Comment by fbartels** [comment]
Minio implements the same api as S3 and would be run in a local docker container as well: https://www.minio.io/

**Comment by fbartels** [comment]
Probably best to add a compose override example.
