### ISSUE TITLE
Issue running Kopano with docker-compose

### ISSUE THREAD

**Issue by rikirenz** [zokradonh/kopano-docker#88]
Hey Guys,
I am using docker-compose on CENTOS 7.
I have cloned the repo and I run the command `docker-compose up`.

But when I try to access the webapp using the username & password: user1, user1 I am not able to login, it just shows the loading logo.

There are 2 errors that makes me wonder something went wrong during the init phase:
1 Error -  Kopano Server:
```
kopano_server| kcoid discovery error: Get https://kopano.demo/.well-known/openid configuration: dial tcp 128.141.210.114:443: connect: no route to host
```
2 Error - DB access warning:

```
db_1| 2019-02-18 16:29:24 18 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
```

any idea?

**Comment by fbartels** [comment]
Hi @rikirenz,

either of these two errors could explain your problems to login. Can you post your .env file?

```
kopano_server| kcoid discovery error: Get https://kopano.demo/.well-known/openid configuration: dial tcp 128.141.210.114:443: connect: no route to host
```

https://github.com/zokradonh/kopano-docker/blob/master/docker-compose.yml-example#L212-L213 should take care that containers relying on the external domain name can always resolve it. Maybe https://github.com/zokradonh/kopano-docker/blob/master/setup.sh#L306 does not resolve to the right ip on centos?

```
db_1| 2019-02-18 16:29:24 18 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
```

For this second error I think I need your `.env`. After running setup.sh you should actually not use `root` to login to mysql, but a user called `kopano`.

**Comment by rikirenz** [comment]
Hey @fbartels,
This is my .env file:
```
# please consult https://github.com/zokradonh/kopano-docker
# for possible configuration values and their impact
CORE_VERSION=latest
WEBAPP_VERSION=latest
ZPUSH_VERSION=latest
KONNECT_VERSION=latest

LDAP_ORGANISATION="Kopano Demo"
LDAP_DOMAIN=kopano.demo
LDAP_BASE_DN=dc=kopano,dc=demo
LDAP_SERVER=ldap://ldap:389
LDAP_ADMIN_PASSWORD=AC4B2206258E9489C9A2453A42A9D1B0
LDAP_READONLY_USER_PASSWORD=1EC3900A219F2184BAAC6B70FEAD725E
LDAP_BIND_DN=cn=readonly,dc=kopano,dc=demo
LDAP_BIND_PW=1EC3900A219F2184BAAC6B70FEAD725E
LDAP_SEARCH_BASE=dc=kopano,dc=demo

# LDAP query filters
LDAP_QUERY_FILTER_USER=(&(kopanoAccount=1)(mail=%s))
LDAP_QUERY_FILTER_GROUP=(&(objectclass=kopano-group)(mail=%s))
LDAP_QUERY_FILTER_ALIAS=(&(kopanoAccount=1)(kopanoAliases=%s))
LDAP_QUERY_FILTER_DOMAIN=(&(|(mail=*@%s)(kopanoAliases=*@%s)))
SASLAUTHD_LDAP_FILTER=(&(kopanoAccount=1)(uid=%s))

# LDAP user password self-service reset settings
SELF_SERVICE_SECRETEKEY=10717E4B986E438A4A28BBAFBFF480F1
SELF_SERVICE_PASSWORD_MIN_LENGTH=5
SELF_SERVICE_PASSWORD_MAX_LENGTH=0
SELF_SERVICE_PASSWORD_MIN_LOWERCASE=0
SELF_SERVICE_PASSWORD_MIN_UPPERCASE=0
SELF_SERVICE_PASSWORD_MIN_DIGIT=1
SELF_SERVICE_PASSWORD_MIN_SPECIAL=1

# switch the value of these two variables to use the activedirectory configuration
KCUNCOMMENT_LDAP_1=!include /usr/share/kopano/ldap.openldap.cfg
KCCOMMENT_LDAP_1=!include /usr/share/kopano/ldap.active-directory.cfg

MYSQL_HOST=db
MYSQL_ROOT_PASSWORD=590EDBC10DBCD9F4925B9BB2AB1ED555
MYSQL_USER=kopano
MYSQL_PASSWORD=C27DBECE661F51F507030A5A8E453167
MYSQL_DATABASE=kopano

KCCONF_SERVER_SERVER_NAME=Kopano

POSTMASTER_ADDRESS=postmaster@kopano.demo
TZ=Europe/Zurich

# Defines how Kopano can be accessed from the outside world
FQDN=kopano.demo
EMAIL=self_signed
HTTP=80
HTTPS=443
LDAPPORT=389

# Settings for test environments
EXTRAHOSTS=kopano.demo:128.141.210.114
INSECURE=yes

# Docker Repository to push to/pull from
docker_repo=zokradonh
COMPOSE_PROJECT_NAME=kopano

# Modify below to build a different version, than the kopano nightly release
#KOPANO_CORE_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/core:/final/Debian_9.0/
#KOPANO_WEBAPP_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/webapp:/final/Debian_9.0/
#KOPANO_WEBAPP_FILES_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/files:/final/Debian_9.0/
#KOPANO_WEBAPP_MDM_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/mdm:/final/Debian_9.0/
#KOPANO_WEBAPP_SMIME_REPOSITORY_URL=https://serial:REPLACE-ME@download.kopano.io/supported/smime:/final/Debian_9.0/
#KOPANO_ZPUSH_REPOSITORY_URL=http://repo.z-hub.io/z-push:/final/Debian_9.0/
#RELEASE_KEY_DOWNLOAD=1
#DOWNLOAD_COMMUNITY_PACKAGES=0

# Additional packages to install
ADDITIONAL_KOPANO_PACKAGES=
ADDITIONAL_KOPANO_WEBAPP_PLUGINS= whatsapp4deskapp
```

**Comment by fbartels** [comment]
Hi @rikirenz,

I have imported your .env file into my local system (while adapting the EXTRAHOSTS line for my local environment) and I was able to start everything up.

My working theory is that for 1 you need to adapt the ip in EXTRAHOSTS to something that docker can internally resolve to your host. For 2 it seems the mysql container was maybe killed to early in its first start and therefore did not complete initialisation.

**Comment by rikirenz** [comment]
@fbartels do you have docker on CENTOS 7 ?

**Comment by fbartels** [comment]
No, all my systems are either Debian or Ubuntu.

**Comment by fbartels** [comment]
Hi @rikirenz,

I've spent some time today trying out these containers on a centos vm and have compiled a list of changes that is now in #89 . Can you give this a quick try to see if this resolves the issue for you as well?

**Comment by rikirenz** [comment]
Hey @fbartels,
Thank you so much for the commit. The error changed but I am still not able to login in the app:
These are the errors I got this time:
```
kopano_kapi              | 2019/02/26 11:26:50 Problem with request: Get http://kopano_konnect:8777/.well-known/openid-configuration: dial tcp: lookup kopano_konnect on 127.0.0.11:53: no such host. Sleeping 1s
```
The db error is still there:
```
db_1                     | 2019-02-26 10:30:36 23 [Warning] Access denied for user 'root'@'localhost' (using password: YES)
```

any ideas? Maybe I am doing something wrong.

Thanks Riccardo

**Comment by fbartels** [comment]
Hmm.. @rikirenz 

Could you try to also delete the data volumes (e.g. `docker-compose down -v` to purge the previously created ssl certificates and the mysql/mariadb volume? 

I would expect that konnect will afterwards be able to start and the mysql error (although unrelated to konnect) could be gone as well.

**Comment by rikirenz** [comment]
@fbartels yes! The problem was with the volume. I thought I purged once I have done the checkout but I was wrong. 
Thanks!

**Comment by fbartels** [comment]
Ok, so lets close this issue then one last time :-D

Thanks for your feedback.
