### ISSUE TITLE
kcoid discovery error

### ISSUE THREAD

**Issue by mhoffmann75** [zokradonh/kopano-docker#92]
With latest containers I cannot get Kopano demo up and running. I end up with:
> kopano_server kcoid discovery error: unexpected response content-type: text/html

Repeating - after 5 mins docker container **kopano_server** exiting itself.

Same setup was running end of January 2019 without problems. Any changes breaking things?

I also tried to recreate all containers, volumes and networks from scratch but ended in similar problems as described here: https://github.com/zokradonh/kopano-docker/issues/88
Although I'm on ubuntu 18.04 LTS.

Any idea what's going on. Has the discovery stuff changed somehow or is it broken in nightly?

**Comment by fbartels** [comment]
Hi @mhoffmann75 ,

I did some changes to the compose file in #89. It seems like the lookup of the discovery document (served through kopano_konnect) is failing in your scenario.

Can you post your current `docker-compose.yml` and `.env`?

**Comment by mhoffmann75** [comment]
I setup a complete fresh Debian buster (testing) with docker.io and docker-compose and now bringing up Kopano docker demo did make no problems. Maybe it is just a problem with ubuntu 18.04 or somehow my ubuntu server got screwed.
Still struggling to get up Caldav for Kopano but that's another story ...

**Comment by fbartels** [comment]
I did a retest with a clean 18.04 meanwhile and here it all worked out of the box.

**Comment by mhoffmann75** [comment]
Ok thanks, than my box is screwed :-)
