### ISSUE TITLE
create admin.cfg via env?

### ISSUE THREAD

**Issue by mhoffmann75** [zokradonh/kopano-docker#99]
I would love to see an improvement to add admin.cfg to kopano_server container via environment variable. This way the demo setup (or productive) would be able to include default_store_locale on setup. Making WebApp look so much better than english only folders :-)

**Comment by fbartels** [comment]
With the above change its now possible to add `KCCONF_ADMIN_DEFAULT_STORE_LOCALE=de_DE.UTF-8
` to the compose file and have future stores created in german.

It would be nice to have this by default in the compose file, let setup.sh ask/check the desired locale and then also make sure that the desired locale exists in the container (https://github.com/zokradonh/kopano-docker/blob/master/core/Dockerfile#L48-L49 could be made obsolete by this).

**Comment by mhoffmann75** [comment]
Yep that was exactly what I had in mind. Thanks for the quick fix.

**Comment by fbartels** [comment]
Closing as the original question has been resolved.
